package com.jagex.protocol.revisions;

public enum LoginResponse742 {
    SUCCESS(2),
    INVALID_LOGIN_OR_PASSWORD(3),
    ACCOUNT_DISABLED(4),
    ACCOUNT_ALREADY_LOGGED_IN(5),
    GAME_UPDATED(6),
    SERVER_FULL(7),
    LOGIN_SERVER_OFFLINE(8),
    LOGIN_LIMIT_EXCEEDED(9),
    BAD_SESSION_ID(10),
    PASSWORD_TOO_COMMON(11),
    MEMBERSHIP_REQUIRED(12),
    LOGIN_FAILED(13),
    SERVER_UPDATING(14),
    INVALID_LOGIN_SERVER(20),
    TOO_MANY_INCORRECT_LOGINS(16),
    STANDING_IN_MEMBERS_AREA(17),
    ACCOUNT_LOCKED(18),
    FULLSCREEN_MEMBERS_ONLY(19),
    MALFORMED_PACKET(22),
    NO_REPLY_FROM_SERVER(23),
    PROFILE_LOAD_ERROR(24),
    UNEXPECTED_SERVER_RESPONSE(25),
    IP_BANNED(26),
    SERVICE_UNAVAILABLE(27),
    COMBAT_LEVEL_TOO_LOW(29),
    NON_MEMBERS_ACCOUNT(30),
    DISPLAY_NAME_REQUIRED(31),
    LOGIN_ATTEMPT_FAILED(32),
    SESSION_EXPIRED(35),
    AUTH_SERVER_OFFLINE(36),
    ACCOUNT_INACCESSIBLE(37),
    INSTANCE_NO_LONGER_EXISTS(39),
    MEMBERS_WORLD_LOGIN_REQUIRED(40),
    INSTANCE_FULL(41),
    SYSTEMS_UNAVAILABLE(44),
    TZHAAR_REQUIREMENTS_NOT_MET(45),
    INSTANCE_MARKED_FOR_DELETION(46),
    EMAIL_VALIDATION_REQUIRED(47),
    SESSION_ENDED(48),
    JAG_LOCKED(50),
    EMAIL_VALIDATION_REQUIRED_2(51),
    TEMP_BANNED(53),
    PVP_REQUIREMENT_NOT_MET(29),
    BOUNTY_REQUIREMENT_NOT_MET(29),
    FIGHT_PITS_REQUIREMENTS_NOT_MET(45),
    MEETING_ROOM_ERROR(45),
    PRIVATE_ROOM_NO_RANK(45),
    PRIVATE_ROOM_NO_INVITE(45);

    public final int code;

    LoginResponse742(int code) {
        this.code = code;
    }

}